version: "3.7"
services:
  db:
    image: postgres:12-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capernaum
      POSTGRES_DB: capernaum
      POSTGRES_PASSWORD: password
