version: '3.4'

services:
  pg:
    image: postgres:11
    container_name: capernaum-db
    environment:
      POSTGRES_DB: capernaum
      POSTGRES_USER: capernaum
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
