---
- name: provision Capernaum
  hosts: webservers
  vars_files:
    - public.yaml
    - secrets.yaml
  become: yes
  tasks:
#    - name: configure modern apt repository for node
#      apt_repository:
#        repo: deb https://deb.nodesource.com/node_12.x bionic main
#        state: present
#
#    - name: install apt packages
#      apt:
#        pkg: "{{ item }}"
#        update_cache: yes
#      loop:
#        - nodejs
#        - git
#        - nginx
#        - postgresql
#        - python3-psycopg2
#        - htop
#        - tree
#        - emacs
#        - multitail
#
#    - name: create database user
#      become_user: postgres
#      postgresql_user:
#        name: capernaum
#        shell: /bin/bash
#        password: password
#
#    - name: create database
#      become_user: postgres
#      postgresql_db:
#        name: capernaum
#        owner: capernaum
#
#    - name: create capernaum user
#      user:
#        name: capernaum
#        password: "{{ 'password' | password_hash('sha512') }}"
#
#    - name: clone application from GitHub
#      become_user: capernaum
#      git:
#        repo: https://github.com/quantum-bits/capernaum.git
#        dest: /home/capernaum/src

    - name: create and copy .env file
      become_user: capernaum
      template:
        src: templates/dot-env.j2
        dest: "{{ server_base_dir }}/.env"
        mode: 0400

    - name: create image upload directory
      become_user: capernaum
      file:
        path: "{{ cap_data_files }}/{{ cap_upload_dir }}"
        state: directory
        mode: 0755

    - name: create generated PDF directory
      become_user: capernaum
      file:
        path: "{{ cap_data_files }}/{{ cap_pdf_dir }}"
        state: directory
        mode: 0755


#    - name: install node modules for user interface
#      become_user: capernaum
#      yarn:
#        path: /home/capernaum/src/ui
#
#    - name: install node modules for server
#      become_user: capernaum
#      yarn:
#        path: /home/capernaum/src/server

#    - name: build production ui
#      become_user: capernaum
#      command:
#        chdir: /home/capernaum/src/ui
#        cmd: yarn build
#        creates: /home/capernaum/src/ui/dist/index.html

#    - name: copy nginx config file
#      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/capernaum
#
#    - name: enable nginx configuration
#      file: >
#        dest=/etc/nginx/sites-enabled/capernaum
#        src=/etc/nginx/sites-available/capernaum
#        state=link
#
#    - name: restart nginx
#      service: name=nginx state=restarted
