---
- name: provision Capernaum
  hosts: webservers
  become: yes
  tasks:
    - name: install apt packages
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      loop:
        - git
        - nginx
        - postgresql
        - python3-psycopg2

    - name: create database user
      become_user: postgres
      postgresql_user:
        name: capernaum
        password: password

    - name: create database
      become_user: postgres
      postgresql_db:
        name: capernaum
        owner: capernaum
