development:
  hosts:
    nurkbook:
      ansible_become: no
      ansible_connection: local
  vars:
    node_env: development
    cap_base_abs_dir: "/Users/tom/Taylor/Projects/Capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}"

staging:
  hosts:
    cap-staging:
      ansible_user: tom
      ansible_host: faraday-effect.com
      server_name: faraday-effect.com
  vars:
    node_env: production
    node_version: 14
    codename: focal
    nginx_config: nginx-production.conf
    cap_base_abs_dir: "/home/capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}/app"

production:
  hosts:
    galilee:
      ansible_user: tnurkkala
      ansible_host: localhost
      ansible_port: 2222
      server_name: galilee.cse.taylor.edu
  vars:
    node_env: production
    node_version: 12
    codename: bionic
    nginx_config: nginx-production.conf
    cap_base_abs_dir: "/home/capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}/app"
