# This is the inventory file.
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

development:
  hosts:
    nurkbook:
      ansible_become: no
      ansible_connection: local
  vars:
    node_env: development
    cap_base_abs_dir: "/Users/tom/Taylor/Projects/Capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}"

staging:
  hosts:
    faraday-effect:
      ansible_user: tom
      ansible_host: faraday-effect.com
      domain_name: faraday-effect.com
      subdomain:
        admin: admin
        group: groups
        ssl: admin
  vars:
    node_env: production
    node_version: 14
    codename: focal
    nginx_config: nginx-production.conf
    cap_base_abs_dir: "/home/capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}/app"
    admin_domain_name: "{{ subdomain.admin }}.{{ domain_name }}"
    group_domain_name: "{{ subdomain.group }}.{{ domain_name }}"
    ssl_domain_name: "{{ subdomain.ssl }}.{{ domain_name }}"

production:
  hosts:
    galilee:
      ansible_user: tnurkkala
      ansible_host: localhost
      ansible_port: 2222
      server_name: galilee.cse.taylor.edu
  vars:
    node_env: production
    node_version: 12
    codename: bionic
    nginx_config: nginx-production.conf
    cap_base_abs_dir: "/home/capernaum"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}/app"
