development:
  hosts:
    localhost:
      ansible_become: no
      ansible_connection: local
  vars:
    node_env: development
    cap_base_dir: "/Users/tom/Taylor/Projects/Capernaum"
    cap_app_dir: "{{ cap_base_dir }}"

staging:
  hosts:
    ubuntu-desktop:
      ansible_user: tom
      ansible_host: 10.211.55.53
      server_name: ubuntu
  vars:
    node_env: production
    nginx_config: nginx-simple.conf
    cap_base_dir: "/home/capernaum"
    cap_app_dir: "{{ cap_base_dir }}/app"

production:
  hosts:
    galilee-via-tunnel:
      # Use this with forwarded port, as in
      #   ssh -L2222:galilee.cse.taylor.edu:22 john.cse.taylor.edu
      ansible_user: tnurkkala
      ansible_host: localhost
      ansible_port: 2222
      server_name: "galilee.cse.taylor.edu"
      proxy:
        host: "10.120.160.77"
        port: 3128
      mail:
        host: smtp.cse.taylor.edu
        from: "Tom Nurkkala <tnurkkala@cse.taylor.edu>"
  vars:
    node_env: production
    nginx_config: nginx-production.conf
    cap_base_dir: "/home/capernaum"
    cap_app_dir: "{{ cap_base_dir }}/app"
