development:
  hosts:
    nurkbook:
      ansible_become: no
      ansible_connection: local
  vars:
    node_env: development
    cap_base_dir: "/Users/tom/Taylor/Projects/Capernaum"
    cap_app_dir: "{{ cap_base_dir }}"

staging:
  hosts:
    ubuntu-desktop:
      ansible_user: tom
      ansible_host: 10.211.55.53
      server_name: ubuntu
  vars:
    node_env: production
    nginx_config: nginx-simple.conf
    cap_base_dir: "/home/capernaum"
    cap_app_dir: "{{ cap_base_dir }}/app"

production:
  hosts:
    galilee:
      ansible_user: tnurkkala
      ansible_host: localhost
      ansible_port: 2222
      server_name: "galilee.cse.taylor.edu"
  vars:
    node_env: production
    nginx_config: nginx-production.conf
    cap_base_dir: "/home/capernaum"
    cap_app_dir: "{{ cap_base_dir }}/app"
