---
- name: pull from Git and restart
  hosts: webservers
  vars_files:
    - public.yaml
    - secrets.yaml
  become: yes
  become_user: "{{ cap_username }}"
  tasks:
    - name: clone application from GitHub
      git:
        repo: "{{ cap_repo }}"
        dest: "{{ cap_src_dir }}"
        clone: no
        update: yes

    - name: create and copy .env file
      template:
        src: templates/dot-env.j2
        dest: "{{ cap_server_dir }}/.env"
        mode: 0400

    - name: install node modules for user interface
      yarn:
        path: "{{ cap_ui_dir }}"

    - name: install node modules for server
      yarn:
        path: "{{ cap_server_dir }}"

    - name: build production ui
      command:
        chdir: "{{ cap_ui_dir }}"
        cmd: yarn build
